name: Ejecutar pruebas E2E

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # =========================
      # INSTALAR WEBAPP SERVER
      # =========================
      - name: Instalar http-server
        run: npm install -g http-server

      # =========================
      # LEVANTAR MINI APP
      # =========================
      - name: Iniciar aplicación
        run: |
          cd webapp
          http-server -p 5500 &
      
      # =========================
      # INSTALAR CYPRESS
      # =========================
      - name: Instalar dependencias Cypress
        run: |
          cd cypress-test
          npm install

      # =========================
      # ESPERAR SERVIDOR
      # =========================
      - name: Esperar servidor
        run: npx wait-on http://127.0.0.1:5500

      # =========================
      # EJECUTAR TESTS
      # =========================
      - name: Ejecutar pruebas Cypress
        run: |
          cd cypress-test
          npx cypress run